"""add_visit_place_name

Revision ID: 6bdbb6e90998
Revises: 043aa3aa5395
Create Date: 2026-02-21 00:16:25.710241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bdbb6e90998'
down_revision: Union[str, Sequence[str], None] = '043aa3aa5395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('place_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'place_name')
    # ### end Alembic commands ###
